---

- name: Check if /usr/local/bin/terraform exists
  stat:
    path: /usr/local/bin/terraform
  register: terraform_bin

- name: Remove /usr/local/bin/terraform (if exists)
  ansible.builtin.file:
    path: /usr/local/bin/terraform
  when: terraform_bin.stat.exists

- name: Download and unarchive Terraform
  ansible.builtin.unarchive:
    src: https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
