---

- name: Check if /usr/local/bin/oauth2-proxy exists
  stat:
    path: /usr/local/bin/oauth2-proxy
  register: oauth2proxy_bin

- name: Remove /usr/local/bin/oauth2-proxy (if exists)
  ansible.builtin.file:
    path: /usr/local/bin/oauth2-proxy
    state: absent
  when: oauth2proxy_bin.stat.exists

- name: Download and unarchive oauth2-proxy
  ansible.builtin.unarchive:
    src: https://github.com/oauth2-proxy/oauth2-proxy/releases/download/v7.1.3/oauth2-proxy-v7.1.3.linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes

- name: Template a file to /etc/oauth2-proxy.cfg
  ansible.builtin.template:
    src: oauth2-proxy.cfg.j2
    dest: /etc/oauth2-proxy.cfg
